### ISSUE TITLE
The work order system needs to support customized classification

### ISSUE THREAD

**Issue by johnnysong-cc** [everwisher/COMP120-Demo#1]
Hey man, I think the work order system needs to support ***customized classification***.

**Comment by everwisher** [comment]
Emm... yeah, I can sense the needs somewhat. But I can't quite elaborate it. Please describe the requirements in detail, okay?

**Comment by johnnysong-cc** [comment]
One thing, to improve efficiency, information regarding this work should be able to be searched by work orders.

**Comment by everwisher** [comment]
Good idea. I have this item added to my to-do list.
